### ISSUE TITLE
gradle dependency

### ISSUE THREAD

**Issue by adriangalera** [kink80/cognitoauth#4]
Hi!
This library is pretty awesome, but it would be great if it is available throught the Maven public repo. For instance to be used as a gradle dependency.
If that sounds good, I can prepare it to export it as a library

**Comment by kink80** [comment]
That sounds awesome, you're welcome to make this contribution.

Thanks,
Slavek

**Comment by adriangalera** [comment]
I performed the changes in pom.xml in order to so and I created the ticket in OSSRH in order they allocate a repository in maven central:
https://issues.sonatype.org/browse/OSSRH-37594
I'll let you know when it's all ready and make the PR

**Comment by kink80** [comment]
Merged, thank you!
